"""entity tables

Revision ID: 57d39b54ce34
Revises: 
Create Date: 2022-05-14 18:53:18.860455

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "00000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_entity",
        sa.Column("child_entity_id", postgresql.UUID(), nullable=False),
        sa.Column("attribute_a", sa.TEXT(), nullable=False),
        sa.Column("attribute_b", sa.Integer(), nullable=False),
        sa.Column("attribute_c", sa.NUMERIC(), nullable=False),
        sa.PrimaryKeyConstraint("child_entity_id"),
    )
    op.create_table(
        "entity",
        sa.Column("entity_id", postgresql.UUID(), nullable=False),
        sa.Column("bar_value_object_attribute_0", sa.TEXT(), nullable=False),
        sa.Column("bar_value_object_attribute_1", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "entity_child_entity",
        sa.Column("entity_child_entity_id", postgresql.UUID(), nullable=False),
        sa.Column("entity_id", postgresql.UUID(), nullable=False),
        sa.Column("child_entity_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ("child_entity_id",),
            ["child_entity.child_entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ("entity_id",),
            ["entity.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_child_entity_id"),
        sa.UniqueConstraint("entity_id", "child_entity_id"),
    )
    op.create_index(
        op.f("ix_entity_child_entity_child_entity_id"),
        "entity_child_entity",
        ["child_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_child_entity_entity_id"),
        "entity_child_entity",
        ["entity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_entity_child_entity_entity_id"), table_name="entity_child_entity"
    )
    op.drop_index(
        op.f("ix_entity_child_entity_child_entity_id"), table_name="entity_child_entity"
    )
    op.drop_table("entity_child_entity")
    op.drop_table("entity")
    op.drop_table("child_entity")
    # ### end Alembic commands ###
